#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# wallpaper
swaybg -i $config/wallpapers/train.jpg &

# effects
$scripts/rgb &

# other
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

hyprctl setcursor Catppuccin-Mocha-Dark-Cursors 24 &
wl-clip-persist --clipboard both &
/usr/lib/polkit-kde-authentication-agent-1 &
